# Generated by Django 4.1.2 on 2022-10-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0002_furniture_state_furniture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
