# Generated by Django 4.1.3 on 2022-11-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='renting.rider'),
        ),
        migrations.AddField(
            model_name='rider',
            name='rented_cars',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='renting.car'),
        ),
    ]
