# Generated by Django 4.1.3 on 2022-11-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_car_rented_by_rider_rented_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='rented_cars',
        ),
        migrations.AddField(
            model_name='car',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renting.admin'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renting.rider'),
        ),
    ]
