version: '3.7'
services:
    mysql:
        image: docker.io/mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todos
        volumes:
            - todo-mysql-data:/var/lib/mysql
        networks:
            - todo-app
    app:
        build:
            context: .
        ports:
            - '3000:3000'
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: todos
        networks:
            - todo-app
        depends_on:
            - mysql

networks:
    todo-app:

volumes:
    todo-mysql-data:
